admin/src/web/forms/user.py
from wtforms.validators import Length, InputRequired, Email, ValidationError
from wtforms import StringField, PasswordField, EmailField, SelectMultipleField
from wtforms.widgets import CheckboxInput, ListWidget
from src.web.forms.base_form import BaseForm
from src.core.auth.repositories.user import get_user_by


class MultiCheckboxField(SelectMultipleField):
    """A multiple-select, except displays a list of checkboxes."""

    widget = ListWidget(prefix_label=False)
    option_widget = CheckboxInput()


class BasicUserForm(BaseForm):
    name = StringField("Nombre", validators=[Length(max=255), InputRequired()])
    surname = StringField("Apellido", validators=[Length(max=255), InputRequired()])
    email = EmailField("Email", validators=[Length(max=255), InputRequired(), Email()])
    username = StringField(
        "Nombre de usuario", validators=[Length(max=255), InputRequired()]
    )
    roles = MultiCheckboxField("Roles", validate_choice=False, choices=[])

    def __init__(self, formdata=..., **kwargs):
        self.user_id = kwargs.pop("user_id", None)
        super().__init__(**kwargs)
        try:
            self["roles"].choices = kwargs["roles"]
            if not self.user_id:
                self["roles"].choices = list(
                    filter(lambda x: x.name != "Socio", self["roles"].choices)
                )
            else:
                r = get_user_by(self.user_id).roles
                is_associate = list(filter(lambda x: x.name == "Socio", r))
                if is_associate == []:
                    self["roles"].choices = list(
                        filter(lambda x: x.name != "Socio", self["roles"].choices)
                    )
                else:
                    self["roles"].choices = is_associate

        except:
            pass

    def validate_email(self, field):
        """Args:
            form (CreateAssociateForm): Form to create a new associate
            field (DNI_number): DNI number of the associate
        Raises:
            ValidationError: If the DNI number is already in use
        Returns:
            Boolean: True if the DNI number is not in use
        """
        if self.user_id:
            if get_user_by(self.user_id).email != field.data and get_user_by(
                field.data, "email"
            ):
                raise ValidationError("Email ya registrado")
        else:
            if get_user_by(field.data, "email"):
                raise ValidationError("Email ya registrado")

        return True

    def validate_username(self, field):
        """Args:
            form (CreateAssociateForm): Form to create a new associate
            field (DNI_number): DNI number of the associate
        Raises:
            ValidationError: If the DNI number is already in use
        Returns:
            Boolean: True if the DNI number is not in use
        """
        if self.user_id:
            if get_user_by(self.user_id).username != field.data:
                raise ValidationError("No se puede cambiar el nombre de usuario")
        else:
            if get_user_by(field.data, "username"):
                raise ValidationError("Nombre de usuario ya registrado")
        return True


class UserForm(BasicUserForm):
    """Form to create a new user
    first_name: First name of the user
    last_name: Last name of the user
    email: Email of the user
    username: Username of the user
    password: Password of the user
    roles: Roles of the user
    """

    password = PasswordField(
        "Contraseña", validators=[Length(max=255), InputRequired()]
    )
    roles = MultiCheckboxField("Roles", validate_choice=False, choices=[])

admin/src/web/controllers/user.py
from cmath import e
from sqlite3 import IntegrityError
from flask import Blueprint, redirect, url_for, request, render_template, flash
from src.core.auth import (
    create_user,
    list_users,
    update_user,
    delete_user,
    get_user_by,
    disable_user,
    enable_user,
    add_role_to_user,
    get_roles,
    get_role,
    remove_role_to_user,
)
from src.web.forms.user import UserForm, BasicUserForm
from passlib.hash import sha256_crypt
from src.web.helpers.form_utils import csrf_remover
from src.web.helpers.auth import has_permission
from src.web.helpers.pagination import pagination_generator

user_blueprint = Blueprint("user", __name__, url_prefix="/usuarios")


@user_blueprint.get("/")
@has_permission("user_index")
def index():
    """Returns:
    HTML: List of users.
    """
    pairs = [
        ("name", "Nombre"),
        ("surname", "Apellido"),
        ("email", "Email"),
        ("username", "Usuario"),
        ("true", "Activo"),
        ("false", "Inactivo"),
    ]
    if request.args.get("column") in ["true", "false"]:
        paginated_query_data = pagination_generator(
            list_users("active", request.args.get("column")), request, "users"
        )
    elif request.args.get("search"):
        paginated_query_data = pagination_generator(
            list_users(request.args.get("column"), request.args.get("search")),
            request,
            "users",
        )
    else:
        paginated_query_data = pagination_generator(list_users(), request, "users")

    return render_template("user/list.html", pairs=pairs, **paginated_query_data)


@user_blueprint.get("/agregar")
@has_permission("user_create")
def get_add():
    """Returns:
    HTML: Form to create a user.
    """
    return render_template("user/add.html", form=UserForm(roles=get_roles()))


@user_blueprint.post("/agregar")
@has_permission("user_create")
def post_add():
    """Returns:
    HTML: Redirect to user list.
    """
    form = UserForm(request.form, roles=get_roles())
    if form.validate():
        form_encp = dict(form.data)
        if form_encp["roles"] == []:
            flash(f"Se deben asignar roles al usuario", category="alert alert-warning")
            return render_template("user/add.html", form=UserForm(roles=get_roles()))

        form_encp["password"] = sha256_crypt.encrypt(form_encp["password"])
        user = create_user(form_encp)
        for role in form_encp["roles"]:
            add_role_to_user(user, get_role(role))
        flash("Usuario creado correctamente", "alert alert-info")
        return redirect(url_for("user.index"))

    else:
        return render_template("user/add.html", form=form)


@user_blueprint.get("/actualizar/<id>")
@has_permission("user_update")
def get_update(id):
    """Args:
        id (int): User id.
    Returns:
        HTML: Form to update a user.
    """
    user = get_user_by(value=id)
    form = BasicUserForm(obj=user, roles=get_roles(), user_id=id)
    return render_template("user/update.html", form=form)


@user_blueprint.post("/actualizar/<id>")
@has_permission("user_update")
def post_update(id):
    """Args:
        id (int): User id.
    Returns:
        HTML: Redirect to user list.
    """
    form = BasicUserForm(request.form, roles=get_roles(), user_id=id)
    if form.validate():
        form = csrf_remover(form.data)
        roles_form = form.pop("roles")
        update_user(id, form)
        user = get_user_by(value=id)
        roles = get_roles()
        if roles_form != []:
            for role in roles:
                if role.name in roles_form:
                    add_role_to_user(user, role)
                else:
                    remove_role_to_user(user, role)
        else:
            flash(f"Se deben asignar roles al usuario", category="alert alert-warning")
            return render_template(
                "user/update.html",
                form=BasicUserForm(obj=user, roles=get_roles(), user_id=id),
            )
        flash("Usuario actualizado correctamente", "alert alert-info")
        return redirect(url_for("user.index"))
    return render_template("user/update.html", form=form)


@user_blueprint.post("/borrar/<id>")
@has_permission("user_destroy")
def delete(id):
    """Args:
        id (int): Id of the user to delete.
    Returns:
        HTML: Redirect to user list.
    """
    flash(f"Se elimino al usuario satisfactoriamente", category="alert alert-warning")
    delete_user(id)
    return redirect(url_for("user.index"))


@user_blueprint.post("/desactivar/<id>")
@has_permission("user_update")
def disable(id):
    """Args:
        id (int): Id of the user to disable.
    Returns:
        HTML: Redirect to user list.
    """
    user = get_user_by(value=id)
    for role in user.roles:
        if role.name == "Admin":
            flash(
                f"No se puede desactivar al usuario {user.username} porque es administrador",
                category="alert alert-warning",
            )
            return redirect(url_for("user.index"))
    flash(
        f"Se deshabilito al usuario satisfactoriamente", category="alert alert-warning"
    )
    disable_user(id)
    return redirect(url_for("user.index"))


# disabling associates
@user_blueprint.post("/activar/<id>")
@has_permission("user_update")
def enable(id):
    """Args:
        id (int): Id of the user to enable.
    Returns:
        HTML: Redirect to user list.
    """
    flash(f"Se habilito al usuario satisfactoriamente", category="alert alert-warning")
    enable_user(id)
    return redirect(url_for("user.index"))

admin/src/web/templates/user/add.html
{% extends "base_form.html" %}
{% set current_template = self._TemplateReference__context.name %}
{% block css %}

{% endblock css %}
{% block title %} Agregar usuario {% endblock title %}

<body>
  {% block header %}
  Agregar usuario
  {% endblock header %}
  {% block form %}
  <form action="{{ url_for('user.post_add') }}" method="POST" class="d-flex flex-column">
    {{ form.hidden_tag() }}
    {% for field in form if field.widget.input_type != 'hidden' %}
    <div class="form-group">
      {% if field.label.text=="Roles" %}
      <p class="form-label">
        {{ field.label.text }}
      </p>
      {% else %}
      {{ field.label(class="form-label") }}
      {% endif %}
      {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button type="submit" class="btn own_golden_bg own_border_radius mt-4">Agregar Usuario</button>
  </form>
  {% endblock form %}
</body>

admin/src/web/templates/user/list.html
{% set current_template = self._TemplateReference__context.name %}
{% extends "base_list.html" %}
{% block title %} Usuarios {% endblock title %}

<body>
  {% block upperbar %}
  {% if has_permission(session["user"],"user_create") %}
  <div class="d-flex align-self-center own_flex_column align-items-center" id="searchHeader">
    <a class="btn own_golden_bg own_add_button" href="{{ url_for('user.get_add') }}" class="d-flex">
      Agregar
    </a>
    {% if has_permission(session["user"],"user_index") %}
    {% include "search.html" %}
    {% endif %}
  </div>
  {% endif %}
  {% endblock upperbar %}

  {% block table %}
  <table class="table table-striped table-bordered">
    <thead>
      <tr class="own_table_header">
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Email</th>
        <th>Usuario</th>
        {% if has_permission(session["user"],"user_update") %}
        <th>Modificar</th>
        {%endif%}
        {% if has_permission(session["user"],"user_update") %}
        <th>Activo</th>
        {%endif%}
        {% if has_permission(session["user"],"user_destroy") %}
        <th>Eliminar</th>
        {%endif%}
      </tr>
    </thead>
    {% if users.items %}
      <tbody>
        {% for user in users.items %}
        <tr class="own_centered">
          <td style="--title1:'Nombre';"> {{ user.name }} </td>
          <td style="--title2:'Apellido';"> {{ user.surname }} </td>
          <td style="--title3:'Email';"> {{ user.email }} </td>
          <td style="--title4:'Usuario';"> {{ user.username }} </td>
          {% if has_permission(session["user"],"user_update") %}
          <td style="--title5:'Modificar'">
            <a class="btn btn-outline-info w-100 p-1 own_options_button"
              href="{{ url_for('user.get_update' ,id=user.id ) }}">
              Mod.
            </a>
          </td>
          {% endif %}
          {% if has_permission(session["user"],"user_update") %}
          <td style="--title6:'Activo'">
            {% if user.active %}
            <form action="{{ url_for('user.disable', id=user.id) }}" method="post">
              <button class="btn btn-outline-success w-100 p-1 own_options_button"
                onclick="return confirm('Seguro que desea inhabilitar a {{ user.first_name }} {{ user.last_name }} ?');">
                Sí
              </button>
            </form>
            {% else %}
            <form action="{{ url_for('user.enable', id=user.id) }}" method="post">
              <button class="btn btn-outline-warning w-100 p-1 own_options_button"
                onclick="return confirm('Seguro que desea habilitar a {{ user.first_name }} {{ user.last_name }} ?');">
                No
              </button>
            </form>
            {% endif %}
          </td>
          {% endif %}
          {% if has_permission(session["user"],"user_destroy") %}
          <td style="--title7:'Eliminar'">
            <form action="{{ url_for('user.delete', id=user.id ) }}" method="post">
              <button type="submit" class="btn btn-outline-danger w-100 p-1 own_options_button" name="Delete"
                value="{{ user.id }}"
                onclick="return confirm('Seguro que desea eliminar {{ user.first_name }} {{ user.last_name }} ?');">
                X
              </button>
            </form>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    {% else %}
      <tbody>
        <tr>
          <td colspan="7" style="text-align: center;" class="own_no_padding_sides">No hay entradas para mostrar</td>
        </tr>
      </tbody>
    {% endif %}
  </table>
  {% endblock table %}
  {% block js %}
  
  <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
  {% endblock js%}
</body>

admin/src/web/templates/user/update.html
{% extends "base_form.html" %}
{% set current_template = self._TemplateReference__context.name %}
{% block css %}

{% endblock css %}
{% block title %} Modificar usuario {% endblock title %}

<body>
  {% block header %}
  Modificar usuario
  {% endblock header %}
  {% block form %}
  <form action="#" method="POST" class="d-flex flex-column ">
    {{ form.hidden_tag() }}
    {% for field in form if field.widget.input_type != 'hidden' %}
    <div class="form-group">
      {% if field.label.text=="Roles" %}
      <p class="form-label">
        {{ field.label.text }}
      </p>
      {% else %}
      {{ field.label(class="form-label") }}
      {% endif %}
      {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button type="submit" class="btn own_golden_bg own_border_radius mt-4">Modificar</button>
  </form>
  {% endblock form %}
</body>