admin/src/web/controllers/associate.py
import os
from src.core.board.repositories.configuration import get_cfg
from werkzeug.utils import secure_filename
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    send_file,
    session,
)
from src.core.board import (
    create_associate,
    delete_associate,
    get_associate_by_id,
    list_associates,
    update_associate,
    add_discipline_to_associate,
    remove_discipline_to_associate,
    get_discipline,
    list_all_associates,
    list_all_disciplines,
    update_associate_profile_pic,
)
from src.core.auth import (
    get_role,
    create_user,
    add_role_to_user,
)

from passlib.hash import sha256_crypt
from src.web.forms.associate import CreateAssociateForm, UpdateAssociateForm
from src.web.helpers.writers import write_csv_file, write_pdf_file
from src.web.helpers.auth import has_permission
from src.web.helpers.pagination import pagination_generator
from src.web.helpers.associate import (
    generate_associate_card,
    is_up_to_date,
    write_pdf_card,
)
from src.web.helpers.pagination import pagination_generator
from src.core.board import get_associate_by_id

associate_blueprint = Blueprint("associate", __name__, url_prefix="/asociados")


# Listing associates
@associate_blueprint.route("/")
@has_permission("associate_index")
def index():
    """Returns:
    HTML: List of associates.
    """
    pairs = [("surname", "Apellido"), ("true", "Activo"), ("false", "Inactivo")]

    if request.args.get("column") in ["true", "false"]:
        paginated_query_data = pagination_generator(
            list_associates("active", request.args.get("column")), request, "associates"
        )
    elif request.args.get("search"):
        paginated_query_data = pagination_generator(
            list_associates(request.args.get("column"), request.args.get("search")),
            request,
            "associates",
        )
    else:
        paginated_query_data = pagination_generator(
            list_associates(), request, "associates"
        )

    return render_template("associate/list.html", pairs=pairs, **paginated_query_data)


# adding associates
@associate_blueprint.get("/agregar")
@has_permission("associate_create")
def get_add():
    """Returns:
    HTML: Form to create an associate.
    """
    return render_template("associate/add.html", form=CreateAssociateForm())


@associate_blueprint.post("/agregar")
@has_permission("associate_create")
def post_add():
    """Returns:
    HTML: Redirect to associate list.
    """
    form = CreateAssociateForm(request.form)
    if form.validate():
        user_dict = dict(form.data)
        user_dict["username"] = user_dict["DNI_number"]
        user_dict["password"] = sha256_crypt.encrypt(user_dict["password"])
        user = create_user(user_dict)
        add_role_to_user(user, get_role("Socio"))
        associate = create_associate(form.data)
        flash(f"Se agregó {associate}", category="alert alert-info")
        return redirect(url_for("associate.index"))
    return render_template("associate/add.html", form=form)


# deleting associates
@associate_blueprint.post("/borrar/<id>")
@has_permission("associate_destroy")
def delete(id):
    """Args:
        id (int): id of the associate
    Returns:
        HTML: Redirect to associate list.
    """
    flash(f"Se elimino al asociado satisfactoriamente", category="alert alert-warning")
    delete_associate(id)
    return redirect(url_for("associate.index"))


# updating associates
@associate_blueprint.get("/actualizar/<id>")
@has_permission("associate_update")
def get_update(id):
    """Args:
        id (int): id of the associate
    Returns:
        _type_: _description_
    """
    associate = get_associate_by_id(id)
    form = UpdateAssociateForm(obj=associate)
    return render_template("associate/update.html", form=form)


# updating associates
@associate_blueprint.post("/actualizar/<id>")
@has_permission("associate_update")
def post_update(id):
    """Args:
        id (int): id of the associate
    Returns:
        HTML: Redirect to associate list.
    """
    form = UpdateAssociateForm(request.form)
    if form.validate():
        flash(f"Se actualizó {get_associate_by_id(id)}", category="alert alert-info")
        update_associate(form.data, id)
        return redirect(url_for("associate.index"))
    return render_template("associate/add.html", form=form)


# csv_writing associates
@associate_blueprint.get("/creador_csv")
@has_permission("associate_index")
def write_csv():
    """Returns:
    CSV: List of associates.
    """
    args = dict(request.args)
    CSV_PATH = os.path.join(os.getcwd(), "public", "Associate_list_report.csv")
    if request.args.get("search"):
        write_csv_file(CSV_PATH, list_all_associates(args["column"], args["search"]))
    else:
        write_csv_file(CSV_PATH, list_all_associates())

    return send_file(CSV_PATH, as_attachment=True)


# pdf_writing associates
@associate_blueprint.get("/creador_pdf")
@has_permission("associate_index")
def write_pdf():
    """Returns:
    PDF: List of associates.
    """
    args = dict(request.args)
    PDF_PATH = os.path.join(os.getcwd(), "public", "Associate_list_report.pdf")
    if request.args.get("search"):
        write_pdf_file(PDF_PATH, list_all_associates(args["column"], args["search"]))
    else:
        write_pdf_file(PDF_PATH, list_all_associates())

    return send_file(PDF_PATH, as_attachment=True)


# add a new discipline to the associate
@associate_blueprint.get("/agregar/<id>")
@has_permission("associate_update")
def add_discipline(id):
    """Args:
        id (int): id of the associate
    Returns:
        HTML: Redirect to associate list.
    """
    associate = get_associate_by_id(id)
    if is_up_to_date(associate):
        pairs = [("name", "Nombre")]

        if request.args.get("search"):
            disciplines = list_all_disciplines(
                request.args.get("column"), request.args.get("search")
            )
        else:
            disciplines = list_all_disciplines()
        return render_template(
            "associate/add_discipline.html",
            pairs=pairs,
            disciplines=disciplines,
            associate=associate,
            currency=get_cfg().currency,
        )

    else:
        flash(
            f"El asociado {associate.name} {associate.surname} esta moroso, no se le puede agregar una disciplina",
            category="alert alert-warning",
        )
        return redirect(url_for("associate.index"))


# add a discipline to the associate
@associate_blueprint.post("/agregar_disciplina/<id>/<discipline_id>")
@has_permission("associate_update")
def register_discipline(id, discipline_id):
    """Args:
        id (int): id of the associate
        discipline_id (int): id of the discipline to add to the associate
    Returns:
        HTML: Redirect to associate list.
    """
    associate = get_associate_by_id(id)
    discipline = get_discipline(discipline_id)

    if discipline.available:
        add_discipline_to_associate(associate, discipline)
        flash(
            f"Se agregó la disciplina {discipline.name} al asociado {associate}",
            category="alert alert-info",
        )
        return redirect(url_for("associate.add_discipline", id=id))

    flash(
        f"La disciplina {discipline.name} no está disponible",
        category="alert alert-danger",
    )
    return redirect(url_for("associate.add_discipline", id=id))


# delete a discipline from the associate
@associate_blueprint.post("/quitar_disciplina/<id>/<discipline_id>")
@has_permission("associate_update")
def delete_discipline(id, discipline_id):
    """Args:
        id (int): id of the associate
        discipline_id (int): id of the discipline to delete from the associate
    Returns:
        HTML: Redirect to associate list.
    """
    associate = get_associate_by_id(id)
    discipline = get_discipline(discipline_id)
    remove_discipline_to_associate(associate, discipline)
    flash(
        f"Se eliminó la disciplina {discipline} del asociado {associate.name} {associate.surname}",
        category="alert alert-info",
    )
    return redirect(url_for("associate.add_discipline", id=id))


# view the associate club card
@associate_blueprint.get("/carnet/<id>")
@has_permission("associate_index")
def club_card_view(id):
    """Args:
        id (int): id of the associate
    Returns:
        HTML: Redirect to associate list.
    """
    associate = get_associate_by_id(id)
    CARD_PATH = os.path.join(os.getcwd(), "public", "associate_card.png")
    QR_PATH = os.path.join(os.getcwd(), "public", "qr.png")
    PROFILE_PIC_PATH = associate.profile_pic
    generate_associate_card(associate, CARD_PATH, PROFILE_PIC_PATH, QR_PATH)
    return render_template("associate/club_card.html", associate=associate)


@associate_blueprint.post("/carnet/<id>")
@has_permission("associate_index")
def club_card_view_post(id):
    """Args:
        id (int): id of the associate
    Returns:
        HTML: Redirect to associate list.
    """
    associate = get_associate_by_id(id)
    image_data = request.files["image"]
    if image_data.filename == "":
        flash(
            "No se subio ninguna foto",
            category="alert alert-danger",
        )
        return redirect(request.url)

    image_data.filename = f"{associate.name}_{associate.surname}_{image_data.filename}"
    secure_filename(image_data.filename)
    profile_path = os.path.join(
        os.getcwd(), "public", "associate_pics", image_data.filename
    )
    image_data.save(profile_path)
    associate.profile_pic = profile_path
    update_associate_profile_pic(associate)

    return redirect(url_for("associate.club_card_view", id=id))


# download the card
@associate_blueprint.post("/carnet_descargar/<id>")
@has_permission("associate_create")
def club_card_download(id):
    """Args:
        id (int): id of the associate
    Returns:
        HTML: Redirect to associate list.

admin/src/web/controllers/user.py
from cmath import e
from sqlite3 import IntegrityError
from flask import Blueprint, redirect, url_for, request, render_template, flash
from src.core.auth import (
    create_user,
    list_users,
    update_user,
    delete_user,
    get_user_by,
    disable_user,
    enable_user,
    add_role_to_user,
    get_roles,
    get_role,
    remove_role_to_user,
)
from src.web.forms.user import UserForm, BasicUserForm
from passlib.hash import sha256_crypt
from src.web.helpers.form_utils import csrf_remover
from src.web.helpers.auth import has_permission
from src.web.helpers.pagination import pagination_generator

user_blueprint = Blueprint("user", __name__, url_prefix="/usuarios")


@user_blueprint.get("/")
@has_permission("user_index")
def index():
    """Returns:
    HTML: List of users.
    """
    pairs = [
        ("name", "Nombre"),
        ("surname", "Apellido"),
        ("email", "Email"),
        ("username", "Usuario"),
        ("true", "Activo"),
        ("false", "Inactivo"),
    ]
    if request.args.get("column") in ["true", "false"]:
        paginated_query_data = pagination_generator(
            list_users("active", request.args.get("column")), request, "users"
        )
    elif request.args.get("search"):
        paginated_query_data = pagination_generator(
            list_users(request.args.get("column"), request.args.get("search")),
            request,
            "users",
        )
    else:
        paginated_query_data = pagination_generator(list_users(), request, "users")

    return render_template("user/list.html", pairs=pairs, **paginated_query_data)


@user_blueprint.get("/agregar")
@has_permission("user_create")
def get_add():
    """Returns:
    HTML: Form to create a user.
    """
    return render_template("user/add.html", form=UserForm(roles=get_roles()))


@user_blueprint.post("/agregar")
@has_permission("user_create")
def post_add():
    """Returns:
    HTML: Redirect to user list.
    """
    form = UserForm(request.form, roles=get_roles())
    if form.validate():
        form_encp = dict(form.data)
        if form_encp["roles"] == []:
            flash(f"Se deben asignar roles al usuario", category="alert alert-warning")
            return render_template("user/add.html", form=UserForm(roles=get_roles()))

        form_encp["password"] = sha256_crypt.encrypt(form_encp["password"])
        user = create_user(form_encp)
        for role in form_encp["roles"]:
            add_role_to_user(user, get_role(role))
        flash("Usuario creado correctamente", "alert alert-info")
        return redirect(url_for("user.index"))

    else:
        return render_template("user/add.html", form=form)


@user_blueprint.get("/actualizar/<id>")
@has_permission("user_update")
def get_update(id):
    """Args:
        id (int): User id.
    Returns:
        HTML: Form to update a user.
    """
    user = get_user_by(value=id)
    form = BasicUserForm(obj=user, roles=get_roles(), user_id=id)
    return render_template("user/update.html", form=form)


@user_blueprint.post("/actualizar/<id>")
@has_permission("user_update")
def post_update(id):
    """Args:
        id (int): User id.
    Returns:
        HTML: Redirect to user list.
    """
    form = BasicUserForm(request.form, roles=get_roles(), user_id=id)
    if form.validate():
        form = csrf_remover(form.data)
        roles_form = form.pop("roles")
        update_user(id, form)
        user = get_user_by(value=id)
        roles = get_roles()
        if roles_form != []:
            for role in roles:
                if role.name in roles_form:
                    add_role_to_user(user, role)
                else:
                    remove_role_to_user(user, role)
        else:
            flash(f"Se deben asignar roles al usuario", category="alert alert-warning")
            return render_template(
                "user/update.html",
                form=BasicUserForm(obj=user, roles=get_roles(), user_id=id),
            )
        flash("Usuario actualizado correctamente", "alert alert-info")
        return redirect(url_for("user.index"))
    return render_template("user/update.html", form=form)


@user_blueprint.post("/borrar/<id>")
@has_permission("user_destroy")
def delete(id):
    """Args:
        id (int): Id of the user to delete.
    Returns:
        HTML: Redirect to user list.
    """
    flash(f"Se elimino al usuario satisfactoriamente", category="alert alert-warning")
    delete_user(id)
    return redirect(url_for("user.index"))


@user_blueprint.post("/desactivar/<id>")
@has_permission("user_update")
def disable(id):
    """Args:
        id (int): Id of the user to disable.
    Returns:
        HTML: Redirect to user list.
    """
    user = get_user_by(value=id)
    for role in user.roles:
        if role.name == "Admin":
            flash(
                f"No se puede desactivar al usuario {user.username} porque es administrador",
                category="alert alert-warning",
            )
            return redirect(url_for("user.index"))
    flash(
        f"Se deshabilito al usuario satisfactoriamente", category="alert alert-warning"
    )
    disable_user(id)
    return redirect(url_for("user.index"))


# disabling associates
@user_blueprint.post("/activar/<id>")
@has_permission("user_update")
def enable(id):
    """Args:
        id (int): Id of the user to enable.
    Returns:
        HTML: Redirect to user list.
    """
    flash(f"Se habilito al usuario satisfactoriamente", category="alert alert-warning")
    enable_user(id)
    return redirect(url_for("user.index"))

admin/src/web/templates/associate/add.html
{% extends "base_form.html" %}
{% set current_template = self._TemplateReference__context.name %}
{% block title %} Agregar asosociado {% endblock title %}

<body>
  {% block header %}
  Agregar asociado
  {% endblock header %}
  {% block form %}
  <form action="{{ url_for('associate.post_add') }}" method="POST" class="d-flex flex-column ">
    {{ form.hidden_tag() }}
    {% for field in form if field.widget.input_type != 'hidden' %}
    <div class="form-group">
      {{ field.label(class="form-label") }}
      {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button type="submit" class="btn own_golden_bg own_border_radius mt-4">Agregar Asociado</button>
  </form>
  {% endblock form %}
</body>

admin/src/web/templates/associate/add_discipline.html
{% set current_template = self._TemplateReference__context.name %}
{% extends "base_list.html" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='fonts/fontawesome-all.min.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/Pretty-Search-Form-.css') }}" />
{% endblock css %}
{% block title %} Agregar Disciplina {% endblock title %}

<body>
  {% block upperbar %}
  <div class="d-flex flex-column align-items-center mt-3" id="searchHeader">
    {% if has_permission(session["user"],"associate_index") %}
    <a class="btn own_golden_bg own_button" href="{{url_for('associate.index')}}">
      Volver al listado
    </a>
    {%endif%}
    {% include "search.html" %}
  </div>
  {% endblock upperbar %}
  {% block table %}
  <table id="example" class="table table-striped table-bordered">
    <thead>
      <tr class="own_table_header">
        <th>Nombre</th>
        <th>Categoría</th>
        <th>Instructores</th>
        <th>Días y horarios</th>
        <th>Costo mensual</th>
        {% if has_permission(session["user"],"associate_update") %}
        <th>Acciones</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for discipline in disciplines %}
      <tr>
        <td style="--title1:'Nombre';"> {{ discipline.name }} </td>
        <td style="--title2:'Categoría';"> {{ discipline.category }} </td>
        <td style="--title3:'Instructores';"> {{ discipline.instructors }} </td>
        <td style="--title4:'Días y horarios';"> {{ discipline.dates }} </td>
        <td style="--title5:'Costo mensual';"> {{ discipline.monthly_cost }} {{ currency }}</td>
        <td style="--title6:'Accion';">
          {% if discipline in associate.disciplines and has_permission(session["user"],"associate_update") %}
          <form action="{{ url_for('associate.delete_discipline', id=associate.id,discipline_id=discipline.id) }}"
            method="post">
            <button class="btn btn-outline-danger w-100 p-1 own_options_button" style="border-radius: 5px" name="Update"
              value="{{ discipline.id }}">
              Dar baja
            </button>
          </form>
          {% elif has_permission(session["user"],"associate_update") %}
          <form action="{{ url_for('associate.register_discipline', id=associate.id,discipline_id=discipline.id) }}"
            method="post">
            <button class="btn btn-outline-info w-100 p-1 own_options_button" style="border-radius: 5px" name="Update"
              value="{{ discipline.id }}">
              Dar alta
            </button>
          </form>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock table %}
  {% block js%}
  {{ super() }}
  <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
  {% endblock js%}
</body>

admin/src/web/templates/associate/club_card.html
{% set current_template = self._TemplateReference__context.name %}
{% extends "base.html" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='fonts/fontawesome-all.min.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/Pretty-Search-Form-.css') }}" />
{% endblock css %}
{% block title %} Carnet de socio {% endblock title %}

<body>
    {% block content %}
    {% include "flashes.html" %}
    <div class="d-flex align-items-center flex-column mt-3 pb-5 justify-content-center w-100 h-100">
        <div class="d-flex flex-column justify-content-center align-items-center" id="searchHeader">
            {% if has_permission(session["user"],"associate_index") %}
            <a class="btn own_golden_bg own_button" href="{{url_for('associate.index')}}">
            Volver al listado
            </a>
            {%endif%}
        </div>

        <div class="flex-row mt-5 justify-content-center align-items-center own_form_title w-50">
            <form method = "POST" enctype = "multipart/form-data" action="{{ url_for('associate.club_card_view_post',id=associate.id) }}">
                <div style="width: 100%" class="d-flex justify-content-center">
                    <input class="form-control" type="file" name="image" id="image" 
                            style="max-width: 400px;" placeholder="Suba foto del asociado"/>
                </div>
                <input class="btn own_golden_bg own_border_radius mb-3 mt-4"type="submit" value="Subir foto"/>
            </form>        
        </div>
        <div class="d-flex flex-column mt-5 justify-content-center align-items-center own_form_title w-100">
            <img src="{{url_for('static', filename='associate_card.png')}}" class="img-fluid mx-auto d-block" alt="Responsive image" >
        </div>

        <form action="{{ url_for('associate.club_card_download', id=associate.id) }}" method="POST" class="d-flex flex-column ">
        <button class="btn own_golden_bg own_border_radius mt-4">Descargar carnet</button>
        </form>
        <form action="{{ url_for('associate.club_card_download_pdf', id=associate.id) }}" method="POST" class="d-flex flex-column ">
            <button class="btn own_golden_bg own_border_radius mt-4">Descargar en PDF</button>
        </form>
    </div>
    {% endblock content %}

  </body>
  

admin/src/web/templates/associate/list.html
{% set current_template = self._TemplateReference__context.name %}
{% extends "base_list.html" %}
{% block title %} Socios {% endblock title %}

<body>
  {% block upperbar %}
  {% if has_permission(session["user"],"associate_create") %}
  <div class="d-flex align-self-center own_flex_column align-items-center" id="searchHeader">
    <a class="btn own_golden_bg own_add_button" href="{{ url_for('associate.get_add') }}">
      Agregar
    </a>
    {% include "search.html" %}
  </div>
  {%endif%}

  <div id="exportSection" class="d-flex align-items-center justify-content-center align-self-center gap-2 pb-4">
    <span class="own_export_text"><b>Exportar:</b></span>
    <div>
      <a href="{{ url_for('associate.write_csv',column=args['column'], search=args['search'] ) }}">
        <img alt="Descargar Excel" src="/public/img/Excel_icon.png" style="height: 50px; margin-right:10px;">
      </a>
      <a href="{{ url_for('associate.write_pdf', column=args['column'], search=args['search'] ) }}">
        <img alt="Descargar PDF" src="/public/img/PDF_icon.png" style="height: 50px;">
      </a>
    </div>
  </div>
  {% endblock upperbar %}

  {% block table %}
  <table class="table table-striped table-bordered ">
    <thead>
      <tr>
        <th style="width: 10vw">Nombre y apellido</th>
        <th> DNI</th>
        <th style="width: 10vw">Domicilio</th>
        <th> Estado</th>
        <th style="width: 15vw">Disciplinas</th>
        {% if has_permission(session["user"],"associate_update") %}
        <th>Modificar</th>
        {%endif%}
        {% if has_permission(session["user"],"associate_update") %}
        <th>Disciplinas</th>
        {%endif%}
        {% if has_permission(session["user"],"payments_create") %}
        <th>Pagar</th>
        {%endif%}
        {% if has_permission(session["user"],"associate_destroy") %}
        <th>Eliminar</th>
        {%endif%}
        {% if has_permission(session["user"],"associate_create") %}
        <th>Carnet</th>
        {%endif%}
      </tr>
    </thead>
    {% if associates.items %}
      <tbody>
        {% for associate in associates.items %}
        <tr>
          <td style="--title1:'Nombre';"> {{ associate.name }} {{ associate.surname }}</td>
          <td style="--title2:'DNI';"> {{ associate.DNI_number }} </td>
          <td style="--title3:'Domicilio';"> {{ associate.address }} </td>
          <td style="--title4:'Estado';"> {% if associate.active %} Activo {% else %} Inactivo {% endif %} </td>
          <td style="--title5:'Disciplinas';"> {% if associate.disciplines %}
            {% for disciplina in associate.disciplines %}
            {{ disciplina.name }} {{ disciplina.category}},
            {% endfor %}
            {% else %}
            No posee
            {% endif %}
          </td>
          {% if has_permission(session["user"],"associate_update") %}
          <td style="--title6:'Modificar';">
            <a class="btn btn-outline-info w-100 p-1 own_options_button"
              href="{{ url_for('associate.get_update' ,id=associate.id) }}">
              Mod.
            </a>
          </td>
          {%endif%}
          {% if has_permission(session["user"],"associate_update") %}
          <td style="--title7:'Asig. Disciplinas';">
            <a class="btn btn-outline-secondary w-100 p-1 own_options_button"
              href="{{ url_for('associate.add_discipline', id=associate.id) }}">
              Asignar
            </a>
          </td>
          {%endif%}
          {% if has_permission(session["user"],"payments_create") %}
          <td style="--title8:'Pagar cuota';">
            <a class="btn btn-outline-success w-100 p-1 own_options_button"
              href="{{ url_for('payments.confirm_payment_get', id=associate.id) }}">
              Pagar
            </a>
          </td>
          {% endif %}
          {% if has_permission(session["user"],"associate_destroy") %}
          <td style="--title9:'Eliminar';">
            <form action="{{ url_for('associate.delete', id=associate.id) }}" method="post">
              <button class="btn btn-outline-danger w-100 p-1 own_options_button"
                onclick="return confirm('Seguro que desea pagar la cuota a {{ associate.name }} {{ associate.surname }} con DNI {{associate.DNI_number}} ?');">
                X
              </button>
            </form>
          </td>
          {%endif%}
          {% if has_permission(session["user"],"associate_create") %}
          <td style="--title10:'Carnet digital';">
            <form action="{{ url_for('associate.club_card_view', id=associate.id) }}" method="get">
              <button class="btn btn-outline-info w-100 p-1 own_options_button">
                Ver
              </button>
            </form>
          </td>
          {%endif%}
        </tr>
        {% endfor %}
      </tbody>
    {% else %}
      <tbody>
        <tr>
          <td colspan="10" style="text-align: center" class="own_no_padding_sides">No hay entradas para mostrar</td>
        </tr>
      </tbody>
    {% endif %}
  </table>
  {% endblock table%}
</body>

admin/src/web/templates/associate/pdf.html
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nombre y apellido</th>
      <th>DNI</th>
      <th>Domicilio</th>
      <th>Estado</th>
      <th>Disciplinas</th>
    </tr>
  </thead>
  <tbody>
    {% for associate in associates %}
    <tr>
      <td> {{ associate.name }} {{ associate.surname }}</td>
      <td> {{ associate.DNI_number }} </td>
      <td> {{ associate.address }} </td>
      <td> {% if associate.active %} Activo {% else %} Inactivo {% endif %} </td>
      <td> {% if associate.disciplines %}
        {% for disciplina in associate.disciplines %}
        {{ disciplina }} ,
        {% endfor %}
        {% else %}
        No esta anotado a disciplinas
        {% endif %}
      </td>
      <td>
        <a class="btn btn-outline-info w-100 p-1" href="{{ url_for('associate.get_update' ,id=associate.id) }}">
          Modificar
        </a>
      </td>
      <td>
        {% if associate.active %}
        <form action="{{ url_for('associate.disable', id=associate.id) }}" method="post">
          <button class="btn btn-outline-danger w-100 p-1" style="border-radius: 5px"
            onclick="return confirm('Seguro que desea inhabilitar a {{ associate.name }} {{ associate.surname }} con DNI {{associate.DNI_number}} ?');">
            Inhabilitar
          </button>
        </form>
        {% else %}
        <form action="{{ url_for('associate.enable', id=associate.id) }}" method="post">
          <button class="btn btn-outline-info w-100 p-1" style="border-radius: 5px"
            onclick="return confirm('Seguro que desea habilitar a {{ associate.name }} {{ associate.surname }} con DNI {{associate.DNI_number}} ?');">
            Habilitar
          </button>
        </form>
        {% endif %}
      </td>
      <td>
        <form action="{{ url_for('associate.delete', id=associate.id) }}" method="post">
          <button class="btn btn-outline-danger w-100 p-1" style="border-radius: 5px"
            onclick="return confirm('Seguro que desea eliminar a {{ associate.name }} {{ associate.surname }} con DNI {{associate.DNI_number}} ?');">
            Eliminar
          </button>
        </form>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>

admin/src/web/templates/associate/update.html
{% extends "base_form.html" %}
{% set current_template = self._TemplateReference__context.name %}
{% block title %} Modificar asociado {% endblock title %}

<body>
  {% block header %}
  Modificar asociado
  {% endblock header %}
  {% block form %}
  <form action="" method="POST" class="d-flex flex-column ">
    {{ form.hidden_tag() }}
    {% for field in form if field.widget.input_type != 'hidden' %}
    <div class="form-group">
      {{ field.label(class="form-label") }}
      {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button type="submit" class="btn own_golden_bg own_border_radius mt-4">Modificar Asociado</button>
  </form>
  {% endblock form %}
</body>