admin/src/web/forms/discipline.py
from wtforms import StringField, DecimalField, SelectField, Label
from wtforms.validators import Length, InputRequired, NumberRange, Regexp
from src.web.forms.base_form import BaseForm

instructor_validator = Regexp(
    regex="^(?:[^\W\d_]|[ ,])+$",
    message="El nombre de un instructor solo puede contener letras y numeros, por favor separe los nombres de varios instructores con una coma",
)


class DisciplineForm(BaseForm):
    """Form to create a new discipline
    name: Name of the discipline
    category: Category of the discipline
    instructors: Name of the instructors
    dates: Dates and hours of the discipline
    monthly_cost: Monthly cost of the discipline
    available: Current availability of the discipline
    """

    name = StringField(
        "Nombre",
        validators=[BaseForm.alphabetic_validator, Length(max=255), InputRequired()],
    )
    category = StringField("Categoría", validators=[Length(max=255), InputRequired()])
    instructors = StringField(
        "Instructores",
        validators=[Length(max=255), InputRequired(), instructor_validator],
        description="Separe los nombres de los instructores con una coma",
    )
    dates = StringField(
        "Días y horarios", validators=[Length(max=255), InputRequired()]
    )
    monthly_cost = DecimalField(
        "Costo mensual",
        validators=[
            InputRequired(),
            NumberRange(0, message="El costo mensual debe ser mayor a 0"),
        ],
    )
    available = SelectField(
        "Disponible", choices=[(True, "Disponible"), ("False", "No disponible")]
    )

admin/src/web/controllers/discipline.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from src.core.board import (
    list_disciplines,
    add_discipline,
    get_discipline,
    delete_discipline,
    update_discipline,
    get_last_discipline,
)
from src.web.forms.discipline import DisciplineForm
from src.web.helpers.auth import has_permission
from src.web.helpers.pagination import pagination_generator
from src.core.board import get_cfg

discipline_blueprint = Blueprint("discipline", __name__, url_prefix="/disciplinas")


@discipline_blueprint.get("/")
@has_permission("discipline_index")
def index():
    """Returns:
    HTML: List of disciplines.
    """
    pairs = [
        ("name", "Nombre"),
        ("category", "Categoría"),
        ("instructors", "Instructores"),
        ("dates", "Días y horarios"),
        ("true", "Disponible"),
        ("false", "No Disponible"),
        ("monthly_cost", "Costo mensual"),
    ]

    if request.args.get("column") in ["true", "false"]:
        paginated_query_data = pagination_generator(
            list_disciplines("available", request.args.get("column")),
            request,
            "disciplines",
        )
    elif request.args.get("search"):
        paginated_query_data = pagination_generator(
            list_disciplines(request.args.get("column"), request.args.get("search")),
            request,
            "disciplines",
        )
    else:
        paginated_query_data = pagination_generator(
            list_disciplines(), request, "disciplines"
        )

    return render_template(
        "discipline/list.html",
        currency=get_cfg().currency,
        pairs=pairs,
        **paginated_query_data,
    )


@discipline_blueprint.get("/agregar")
@has_permission("discipline_create")
def get_add():
    """Returns:
    HTML: Form to create a discipline.
    """
    return render_template("discipline/add.html", form=DisciplineForm())


@discipline_blueprint.post("/agregar")
@has_permission("discipline_create")
def post_add():
    """Returns:
    HTML: Redirect to discipline list.
    """
    form = DisciplineForm(request.form)
    if form.validate():
        add_discipline(form.data)
        flash(f"Se agregó {get_last_discipline()}", category="alert alert-info")
        return redirect(url_for("discipline.index"))
    else:
        return render_template("discipline/add.html", form=form)


@discipline_blueprint.get("/actualizar/<id>")
@has_permission("discipline_update")
def get_update(id):
    """Args:
        id (int): id of the discipline
    Returns:
        HTML: Form to update a discipline.
    """
    return render_template(
        "discipline/update.html", form=DisciplineForm(obj=get_discipline(id))
    )


@discipline_blueprint.post("/actualizar/<id>")
@has_permission("discipline_update")
def update(id):
    """Args:
        id (int): id of the discipline
    Returns:
        HTML: Redirect to discipline list.
    """
    form = DisciplineForm(request.form)
    if form.validate():
        flash(f"Se actualizó {get_discipline(id)}", category="alert alert-info")
        update_discipline(id, form.data)
        return redirect(url_for("discipline.index"))
    else:
        return render_template("discipline/update.html", form=form)


@discipline_blueprint.post("/borrar/<id>")
@has_permission("discipline_destroy")
def delete(id):
    """Args:
        id (int): id of the discipline
    Returns:
        HTML: Redirect to discipline list.
    """
    flash(
        f"Se elimino {get_discipline(request.form['Delete'])}",
        category="alert alert-warning",
    )
    delete_discipline(id)
    return redirect(url_for("discipline.index"))

admin/src/web/templates/discipline/add.html
{% extends "base_form.html" %}
{% set current_template = self._TemplateReference__context.name %}
{% block title %} Agregar disciplina {% endblock title %}

<body>
  {% block header %}
  Agregar disciplina
  {% endblock header %}
  {% block form %}
  <form action="{{ url_for('discipline.post_add') }}" method="POST" class="d-flex flex-column">
    {{ form.hidden_tag() }}
    {% for field in form if field.widget.input_type != 'hidden' %}
    <div class="form-group">
      {{ field.label(class="form-label") }}
      {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button type="submit" class="btn own_golden_bg own_border_radius mt-4">Agregar Disciplina</button>
  </form>
  {% endblock form %}
</body>

admin/src/web/templates/discipline/list.html
{% set current_template = self._TemplateReference__context.name %}
{% extends "base_list.html" %}
{% block title %} Disciplinas {% endblock title %}

<body>
  {% block upperbar %}
  {% if has_permission(session["user"],"discipline_create") %}
  <div class="d-flex align-self-center own_flex_column align-items-center" id="searchHeader">
    <a class="btn own_golden_bg own_add_button" href="{{ url_for('discipline.get_add') }}">
      Agregar
    </a>
    {% if has_permission(session["user"],"discipline_index") %}
    {% include "search.html" %}
    {% endif %}
  </div>
  {% endif %}
  {% endblock upperbar %}

  {% block table %}
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Categoría</th>
        <th>Instructores</th>
        <th>Días y horarios</th>
        <th>Costo mensual</th>
        <th>Cupo</th>
        {% if has_permission(session["user"],"discipline_update") %}
        <th>Modificar</th>
        {%endif%}
        {% if has_permission(session["user"],"discipline_destroy") %}
        <th>Eliminar</th>
        {%endif%}
      </tr>
    </thead>
    {% if disciplines.items %}
      <tbody>
        {% for discipline in disciplines.items %}
        <tr>
          <td style="--title1:'Nombre';"> {{ discipline.name }} </td>
          <td style="--title2:'Categoría';"> {{ discipline.category }} </td>
          <td style="--title3:'Instructores';"> {{ discipline.instructors }} </td>
          <td style="--title4:'Fechas';"> {{ discipline.dates }} </td>
          <td style="--title5:'Costo mensual';"> {{ discipline.monthly_cost }} {{ currency }} </td>
          <td style="--title6:'Cupo';"> {{ "Si" if discipline.available else "No" }} </td>
          {% if has_permission(session["user"],"discipline_update") %}
          <td style="--title7:'Modificar';">
            <a class="btn btn-outline-info w-100 p-1 own_options_button"
              href="{{ url_for('discipline.update', id=discipline.id) }}">
              Mod.
            </a>
          </td>
          {%endif%}
          {% if has_permission(session["user"],"discipline_destroy") %}
          <td style="--title8:'Eliminar';">
            <form action="{{ url_for('discipline.delete', id=discipline.id) }}" method="post">
              <button type="submit" class="btn btn-outline-danger w-100 p-1 own_options_button" style="border-radius: 5px"
                name="Delete" value="{{ discipline.id }}"
                onclick="return confirm('Seguro que desea eliminar {{ discipline.name }} {{ discipline.category }} ?');">
                X
              </button>
            </form>
          </td>
          {%endif%}
        </tr>
        {% endfor %}
      </tbody>
    {% else %}
      <tbody>
        <tr>
          <td colspan="8" style="text-align: center;" class="own_no_padding_sides">No hay entradas para mostrar</td>
        </tr>
      </tbody>
    {% endif %}
  </table>
  {% endblock table %}
  {% block js %}
  <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
  
  {% endblock js %}
</body>

admin/src/web/templates/discipline/update.html
{% extends "base_form.html" %}
{% set current_template = self._TemplateReference__context.name %}
{% block title %} Modificar disciplina {% endblock title %}

<body>
  {% block header %}
  Modificar disciplina
  {% endblock header %}
  {% block form %}
  <form action="#" method="POST" class="d-flex flex-column ">
    {{ form.hidden_tag() }}
    {% for field in form if field.widget.input_type != 'hidden' %}
    <div class="form-group">
      {{ field.label(class="form-label") }}
      {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button type="submit" class="btn own_golden_bg own_border_radius mt-4">Modificar Disciplina</button>
  </form>
  {% endblock form %}
</body>